name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: mkdir-build
      run:
          mkdir -p build
    - name: cd
      run:
          cd build
    - name: cmake-configure
      run: cmake ../
    - name: make
      run: make
    - name: install
      run: make install
    - name: unit-test
      run: ./run_test.sh
